// Table and field IDs for the "Samyou USA" Airtable base.
// Generated by inspecting the base schema. If you rename/add fields in
// Airtable, update the relevant IDs here (find them via the Airtable API
// or the existing get_table_schema output) — the app addresses fields by
// ID so renaming a column label in Airtable won't break it, but adding a
// genuinely new field requires a new entry here.

module.exports = {
  baseId: process.env.AIRTABLE_BASE_ID,

  tables: {
    company: {
      id: 'tblavQufWZinzQRWy',
      fields: {
        name: 'fldGzTLuTR3mYVpGa',
        logo: 'fldazo71UrxYwexRc',
        person: 'fldV7KwZcMMMdHiAW',
        billingAddress: 'fldR7sWSAU7ZyMjfk',
        industry: 'fldLa39Bn78lorYcD',
        status: 'fld4nkOPfgMwAj3YV',
        web: 'fldCK5iBcsXcXeTVf',
        owner: 'fldJEjdBhOObebMWV',
        notes: 'fldlScEcMVM3KsuG2',
        activities: 'fldPy8dGFs3fxA8Kj',
        deals: 'fldrKJPK3HEZCuu2F',
        projects: 'fldyfDdmWXxyn6Ycu'
      },
      statusChoices: ['Planned', 'Lead', 'Client'],
      industryChoices: ['IT', 'AC Manufacturer', 'HVAC+R', 'Compressors', 'Controllers', 'RV AC', 'Transportation/trucking/railroad', 'Dehumidifier', 'Heat Pump']
    },

    contacts: {
      id: 'tblWbRlEAFBc41RlK',
      fields: {
        firstName: 'fldA0kWZUaLYvQX6Y',
        lastName: 'fld5qgZrvmZnWOt1P',
        company: 'fldzo5Wgzte4uSFYd',
        title: 'fldhabWeDUFtQzm3O',
        phone: 'fldPWqLOKpdxjftRD',
        email: 'fld3KrGu8jkXPKKyQ',
        status: 'fldDrBYwrVlvaN3m0',
        notes: 'fldw6DU8fdJ62ASfk',
        deals: 'fldQqwxKfFXTLthAD',
        activities: 'fldUCJ1dHK5Xqe4qq'
      },
      statusChoices: ['Lead', 'Client']
    },

    activities: {
      id: 'tblSN6XimwDVwEfO6',
      fields: {
        name: 'fldxJTnYvbfQfVZLH',
        date: 'fldfZCZfC92rRisOY',
        type: 'fld3u8ayKYMcd1P1q',
        details: 'fldyo0CWMlfmxStw1',
        regarding: 'fldTIzMRqcDacJOV6',
        remind: 'fldhYswz6O3AXrWqE',
        owner: 'fldUfVJnUTs781nbI',
        company: 'fldxDBSuK2LaRo9Jg',
        result: 'fld3M9u0m81wiy3CB',
        file: 'fldnKkEytKb27KJwI',
        attendee: 'fldyer8lg164gj4jM',
        project: 'fldh4U0wV2Q3Nx6wU',
        emailSubject: 'fldI3RqImAjsHZAyh',
        emailDate: 'fldntcoREJLRtN5cH',
        emailMessageId: 'fldtWZpn60JJL3mZi',
        deal: 'fldPwm2ZX17Q37HoB'
      },
      typeChoices: ['To Do', 'Call', 'Email', 'Meeting', 'Demo', 'Completed', 'LinkedIn'],
      resultChoices: ['Not Reachable', 'Scheduled', 'No reply', 'Completed', 'Accept connection']
    },

    deals: {
      id: 'tblACVaQVN4orI0ml',
      fields: {
        name: 'fldgtbW6m6jn5WsbX',
        owner: 'fldstQ5tiEFQ7EvDO',
        company: 'fldXHQkcbAV0gxZv1',
        primaryContact: 'fldHkejpCHDPoleIZ',
        stage: 'fldgndBq6TPkw4b0q',
        amount: 'fldlCKaH88OwCkkNN',
        probability: 'fld5sPnI5PiLDaSqu',
        closeDate: 'fldEyoznWjGQ9rxK3',
        createdDate: 'flds1h0FKvyTwgcIw',
        projects: 'fldX7b3Nw0FKAUo3r',
        products: 'fldMVGhGMm2YeAPCo'
      },
      stageChoices: ['Prospecting', 'Qualification', 'Needs Analysis', 'Proposal', 'Closed Won', 'Closed Lost']
    },

    projects: {
      id: 'tblYTrkR4AeyhWWWl',
      fields: {
        name: 'fldP0a6rCzy1fkDcn',
        status: 'fld0ERl7v2yTm4rzi',
        relatedProduct: 'fld9C85quzOFlpf1y',
        relatedCompany: 'fldpZpaKkEV9X40Fu',
        description: 'fldgNlYU6r0prKogV',
        startDate: 'fldwLuhfAJrqlseAV',
        endDate: 'fldCQ8wP6VLbP9FUA',
        projectActivities: 'fldTMVtbwEAFDDYnw',
        category: 'fldTRA7IgyVRnUA5B',
        linkedActivities: 'fldqDqs6OYSxPYxHL',
        attachments: 'fld8tzOpaNKGpniNJ'
      },
      statusChoices: ['Planned', 'In Progress', 'Completed', 'On Hold', 'Cancelled'],
      categoryChoices: ['Commercial Hot Water', 'Heat Pump', 'Window AC', 'Samyou Internal Project']
    },

    products: {
      id: 'tblC0Hd2nTaduzcJb',
      fields: {
        name: 'fldfHBPsNacbafNVy',
        notes: 'fldP30xMA5n1RvvbZ',
        datasheet: 'fldYoBE6Cns4H4EMu',
        phase: 'fldCrpstD42UpURpi',
        category: 'fldWZWS4qvpYH3f2K',
        image: 'fldFxp2EX1XvzDkYp',
        projects: 'fldXaO9K30XtDaBJ6',
        inputVoltage: 'fldPP4brKY61UwgiG',
        boardSize: 'fld5QdheyAvJ65xNx',
        horsePower: 'flduPBallFkQDvujT',
        maxInputPower: 'fldAk8llEdSBNq45I',
        maxInputCurrent: 'fldx4yKvffbmORsyW',
        maxOutputCurrent: 'fldxRUTRIC75c9seD'
      },
      phaseChoices: ['1 Phase', '3 Phase'],
      categoryChoices: ['DC Inverter Driver', 'Inverter Drive', 'Controller']
    },

    projectActivities: {
      id: 'tblQEEpGJO4j9jY1V',
      fields: {
        name: 'fldR1Ei1ojunNolLH',
        project: 'fldMkvde5GrFeb7yf',
        records: 'fldzsLlupZl09SBMl',
        date: 'fldPxekKpsyf5kJQF',
        type: 'flduX3l5ffkh0lill',
        details: 'fldi92Ej71f2fFjoo',
        deadline: 'fldL05rBnrEE4j2Xh',
        owner: 'fldXMapWgW02YcdIG',
        assigned: 'fldJHH63jdpFJNFef',
        status: 'fldZKUabHXFvPi4J8',
        attachments: 'fldAvd4ZxTCJKpHfj',
        emailSubject: 'fldZxV6mg7ybPRstS',
        emailDate: 'fldpZgN5NQMlCcqPt',
        emailMessageId: 'fldsCSVfzqFowEKd4'
      },
      typeChoices: ['To Do', 'Call', 'Email', 'Meeting', 'Demo', 'Completed', 'In Progress', 'Service Visit'],
      statusChoices: ['Not Started', 'In Progress', 'Completed', 'Overdue']
    },

    projectActivityRecords: {
      id: 'tbltLdQsWxlWrYou7',
      fields: {
        name: 'fldUCs9pWajVFyqxM',
        projectActivity: 'fldsCB9AAxk5gx7X0',
        dateRecorded: 'fldfrVaJpQJKMnRuQ',
        details: 'fldigLoAmWWF8wv0P',
        attachment: 'fldmpvLCgS714zzEZ',
        recordedBy: 'fldNsaok73UutgrjK',
        category: 'fld9Y7uAcESsCUejk'
      },
      categoryChoices: ['Progress Update', 'Issue', 'Decision', 'Resource', 'Document', 'Other']
    },

    taskComments: {
      id: 'tblh9Li0zakzMEVLM',
      fields: {
        comment: 'fldwh0iNRxhXe1rEK',
        author: 'fldODHUooeS3d1VDq',
        link: 'fldz7NW9cKSSI8pJJ',
        task: 'fldTgIhS4uGf0blMd',
        activity: 'fldUu5YRaFLwbM3HI',
        deal: 'fldJfipTntKurG3J7',
        contact: 'fldToadgNohFbScz7',
        project: 'fldunRVicUBJE5WbS',
        attachment: 'fldl7jBSBavdrbJRF',
        postedAt: 'fldm9TvJ0IXEZgedq'
      }
    }
  }
};
